name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "deklerk@dkbasson.com"
          git config --global user.name "Deklerk Basson"

      - name: Deploy to GitHub Pages
        run: gh-pages -d dist -r https://${{ secrets.GITHUB_TOKEN }}@github.com/DKBasson/ThreeJS-Earth.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
